<?xml version="1.0" encoding="utf-8"?><Database Name="attendance" Class="AttandanceContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VP-GULF-DEV-170\SQLEXPRESS;Initial Catalog=attendance;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AttendanceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.attendance" Member="attendances">
    <Type Name="attendance">
      <Column Name="adate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="weekno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fcode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="admno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="remarks" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="RoleId" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.batches" Member="batches">
    <Type Name="batch">
      <Column Name="bcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="course" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="semno" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.faculty" Member="faculties">
    <Type Name="faculty">
      <Column Name="fcode" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="pwd" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="dept" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.schedule" Member="schedules">
    <Type Name="schedule">
      <Column Name="weekno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fcode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="scode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.students" Member="students">
    <Type Name="student">
      <Column Name="admno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubjectDate" Member="SubjectDates">
    <Type Name="SubjectDate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubjectCode" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.subjects" Member="subjects">
    <Type Name="subject">
      <Column Name="scode" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="sname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sysdiagrams" Member="sysdiagrams">
    <Type Name="sysdiagram">
      <Column Name="name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="diagram_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="definition" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tblFiles" Member="tblFiles">
    <Type Name="tblFile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContentType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>